architecture: x86_64
config:
  image.architecture: amd64
  image.description: Nixos 25.05 amd64 (20250704_01:00)
  image.os: Nixos
  image.release: "25.05"
  image.requirements.secureboot: "false"
  image.serial: "20250704_01:00"
  image.type: disk-kvm.img
  image.variant: default
  limits.memory: 8GB
  security.secureboot: "false"
  volatile.base_image: e720b5d0b00ec250c314a04487bca0013c5f99220351e51aea17e6cde1c47cc9
  volatile.cloud-init.instance-id: 7285944e-b726-4e8c-8513-4b8dc32a93bc
  volatile.eth0.host_name: tap8f3e6b5a
  volatile.eth0.hwaddr: 10:66:6a:22:36:8e
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: 0385f540-061c-4ccd-b879-6a00122f413c
  volatile.uuid.generation: 0385f540-061c-4ccd-b879-6a00122f413c
  volatile.vm.definition: pc-q35-9.2
  volatile.vsock_id: "1694425542"
devices:
  eth0:
    network: incusbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
    size: 50GiB
  shared:
    path: /home/app-builder/sources
    source: /home/glenn/w
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
