# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ modulesPath, config, pkgs,... }:

{
  imports = [
    # Include the default incus configuration.
    "${modulesPath}/virtualisation/incus-virtual-machine.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
  ];

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  environment.systemPackages = with pkgs; [
    git
    btop
    neovim
    curl
    wget
    docker
  ];
  nix.settings.trusted-users = ["root" "app-builder"];
  systemd.network = {
    enable = true;
    networks."50-enp5s0" = {
      matchConfig.Name = "enp5s0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  users.users.app-builder = {
    isNormalUser = true;
    description = "Application builder";
    extraGroups = ["wheel" "docker"];
    password = "";
  };

  virtualisation.docker = {
    enable = true; 
    rootless = {
	    enable = true;
	    setSocketVariable = true;
	  };
   };
  system.stateVersion = "25.05"; # Did you read the comment?
}
